### ISSUE TITLE
application.yml Wrong Configuration

### ISSUE THREAD

**Issue by CloudLasting** [choerodon/config-server#1]
version:0.6.0.RELEASE.
```
binder:
  binder:
    brokers: 127.0.0.1:9092
    zkNodes: 127.0.0.1:2181
```
Wrong config here？The correct Configuration should be like this？
```
binder:
  brokers: 127.0.0.1:9092
  zk-nodes: 127.0.0.1:2181
```
it works for me,whatever...
